name: lifelight_festivals
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.2+25

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.0.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  shared_preferences: ^2.3.1
  supabase_flutter: ^2.6.0
  youtube_player_flutter: ^9.0.3
  onesignal_flutter: ^5.2.3
  package_info_plus: ^8.0.2
  google_fonts: ^6.2.1
  upgrader: ^10.3.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/theme.json
    - assets/button_config.json
    - assets/icons/
    - assets/images/
    - .env
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
          style: italic
    - family: HelveticaNeueLT
      fonts:
        - asset: assets/fonts/HelveticaNeueLTStd93BlackOblique.otf