name: lifelight_app
description: "LifeLight Festivals App"
publish_to: 'none'
version: 1.3.2+10

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  json_theme: ^6.4.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.3.4
  onesignal_flutter: ^5.0.4
  timezone: ^0.9.2
  intl: ^0.19.0
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0
  flutter_dotenv: ^5.1.0
  uuid: ^3.0.5
  random_string: ^2.1.0
  url_launcher: ^6.2.6
  provider: ^6.1.2
  overlay_support: ^2.1.0
  flutter_spinkit: ^5.2.1
  another_flushbar: ^1.12.30
  flutter_easyloading: ^3.0.5
  collection: ^1.18.0
  font_awesome_flutter: ^10.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  background_location: ^0.13.0
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.5
  flutter_platform_widgets: ^7.0.0
  auto_size_text: ^3.0.0
  upgrader: ^10.3.0
  package_info_plus: ^8.0.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/theme.json
    - .env
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
          style: italic
    - family: HelveticaNeueLT
      fonts:
        - asset: assets/fonts/HelveticaNeueLTStd93BlackOblique.otf