name: lifelight_app
description: "Life Light App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  google_fonts: ^6.2.1
  json_theme: ^6.4.1
  location: ^5.0.0
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.3.4
  onesignal_flutter: ^5.0.4
  timezone: ^0.9.2
  intl: ^0.19.0
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/theme.json
    - .env